project:
  type: website
  output-dir: _site

website:
  title: "NASDAQ Weekly Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    css: styles.css
    toc: FALSE
